# Generated by Django 5.0.3 on 2024-03-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tblemployeeprofile1',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('gridno', models.IntegerField(blank=True, db_column='GridNo', null=True)),
                ('txtmiddlename', models.CharField(blank=True, db_column='txtMiddleName', max_length=27, null=True)),
                ('txtsurname', models.CharField(blank=True, db_column='txtSurname', max_length=29, null=True)),
                ('dtmdob', models.CharField(blank=True, db_column='dtmDOB', max_length=15, null=True)),
                ('lkpgender', models.CharField(blank=True, db_column='lkpGender', max_length=1, null=True)),
                ('txtfnpfno', models.CharField(blank=True, db_column='txtFNPFNo', max_length=36, null=True)),
                ('txttinno', models.CharField(blank=True, db_column='txtTinNo', max_length=18, null=True)),
                ('intmobile', models.CharField(blank=True, db_column='intMobile', max_length=23, null=True)),
                ('txtmn', models.CharField(blank=True, db_column='txtMN', max_length=51, null=True)),
                ('txtfn', models.CharField(blank=True, db_column='txtFN', max_length=45, null=True)),
                ('txtstreetaddress', models.CharField(blank=True, db_column='txtStreetAddress', max_length=57, null=True)),
                ('lkparea', models.CharField(blank=True, db_column='lkpArea', max_length=2, null=True)),
                ('town_city', models.CharField(blank=True, db_column='Town/City', max_length=2, null=True)),
                ('lkpstatus', models.CharField(blank=True, db_column='lkpStatus', max_length=1, null=True)),
                ('dtmstartdate', models.CharField(blank=True, db_column='dtmStartDate', max_length=15, null=True)),
                ('lkpexittype', models.CharField(blank=True, db_column='lkpExitType', max_length=11, null=True)),
                ('dtmexitdate', models.CharField(blank=True, db_column='dtmExitDate', max_length=15, null=True)),
                ('lkppoliceclearence', models.CharField(blank=True, db_column='lkpPoliceClearence', max_length=1, null=True)),
                ('lkpcategory', models.CharField(blank=True, db_column='lkpCategory', max_length=5, null=True)),
                ('lkpmaritalstatus', models.CharField(blank=True, db_column='lkpMaritalStatus', max_length=1, null=True)),
                ('txtspousename', models.CharField(blank=True, db_column='txtSpouseName', max_length=35, null=True)),
                ('txtspousedob', models.CharField(blank=True, db_column='txtSpouseDoB', max_length=10, null=True)),
                ('intspousephone', models.CharField(blank=True, db_column='intSpousePhone', max_length=35, null=True)),
                ('lkpjobtitle', models.CharField(blank=True, db_column='lkpJobTitle', max_length=2, null=True)),
                ('attphoto', models.CharField(blank=True, db_column='attPhoto', max_length=34, null=True)),
                ('lkpfuneralassistance', models.CharField(blank=True, db_column='lkpFuneralAssistance', max_length=7, null=True)),
                ('lkpnuw', models.CharField(blank=True, db_column='lkpNUW', max_length=3, null=True)),
                ('txtnextofkin', models.CharField(blank=True, db_column='txtNextOfKin', max_length=32, null=True)),
                ('lkprelevantexperience', models.CharField(blank=True, db_column='lkpRelevantExperience', max_length=1, null=True)),
                ('intweight', models.CharField(blank=True, db_column='intWeight', max_length=1, null=True)),
                ('intheight', models.CharField(blank=True, db_column='intHeight', max_length=1, null=True)),
            ],
            options={
                'db_table': 'tblemployeeprofile__1_',
                'managed': False,
            },
        ),
    ]
