# Generated by Django 5.0.3 on 2024-03-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lkptblgender',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=255, null=True)),
            ],
            options={
                'db_table': 'lkptblgender',
                'managed': False,
            },
        ),
    ]
